name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: install
        run: pnpm i

      - name: install vsce
        run: pnpm add -g @vscode/vsce

      - name: publish
        run: |
          pnpm run vsce:package
          pnpm run vsce:publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
