on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release-created }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: install
        run: pnpm i

      - name: install vsce
        run: pnpm add -g @vscode/vsce

      - name: publish
        run: |
          pnpm run vsce:package
          pnpm run vsce:publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
